populationgenomics/team-docs

getting_started.md

Also fixed some punctuation that my PyCharm spellchecker highlighted :)

Reviewing: if left comments, leave merging to the author

---

storage_policies/README.md

Hopefully made bucket descriptions/differences more obvious

Tidy up bucket descriptions

---

python_code_style.md

Vlad, for trailing whitespaces can you see if one of these options works in PyCharm? https://stackoverflow.com/questions/20679842/remove-trailing-whitespace-on-save-in-intellij-idea-12
I'll disable the line length in markdownlint - see #21.

fix linting

---

hail_batch_dev.md

Hey @lgruen, these are minor changes on-top of your other PR.
Feel free to close / merge, I'll merge your PR when this moves into a final state.

Minor comments for clarity

---

new_repository.md

Also fix the table of contents.

Release docs: add a pointer to cpg::hail release docs

---

hail_batch_dev.md

Corresponding implementation change in https://github.com/populationgenomics/hail/pull/44.

Add Hail "prod deploy" docs

---

hail_batch_dev.md

Document Terraform state usage

---

hail_batch_dev.md

Thanks a lot to @vladsaveliev for help in tracking this down.

A token is a session

---

getting_started.md

Add link to hands-on hail tutorial playlist.

Add workshop link

---

hail_batch_dev.md

See https://github.com/populationgenomics/hail/pull/60.

Note that prod deploy is run automatically

---

bioinformatics/reference_data.md

Roughly started keeping track of reference data.

Reference data documentation

---

hail_batch_dev.md

Notes that were stuck in a sublime text, now in docs form.

Add sync information for Hail development

---

storage_policies/README.md

See https://github.com/populationgenomics/analysis-runner/pull/49 for context.

Describe the "test" access level

---

bioinformatics/reference_data.md

- add `delly_human.hg38.excl.tsv`

 Update reference data

---

storage_policies/README.md

Find it helpful for quicker viewing.

Summarise analysis-runner access levels

---

code_editors.md

Add WDL to code_editors

---

storage_policies/README.md

See https://github.com/populationgenomics/analysis-runner/pull/113 for context.

Update `analysis` bucket description to listing-only for humans

---

storage_policies/README.md

Depends on https://github.com/populationgenomics/team-docs/pull/94.

Add description of web bucket links

---

notebooks.md

Add GCS Connector instructions

---

hail_batch_dev.md

Context: https://centrepopgen.slack.com/archives/C018KFBCR1C/p1625624947381700?thread_ts=1625456450.353500&cid=C018KFBCR1C

Note AR permissions required for dev GSAs

---

storage_policies/README.md

Documents https://github.com/populationgenomics/analysis-runner/pull/175.

Update `upload` bucket permissions

---

storage_policies/README.md

Mention web-access groups in documentation

---

storage_policies/README.md

Context: https://github.com/populationgenomics/analysis-runner/pull/192

Mention dependent datasets in the storage policies

---

storage_policies/README.md

Context: https://github.com/populationgenomics/analysis-runner/pull/195

Update upload bucket docs

---

getting_started.md

Noted issues with installing hail, resolved through a python downgrade. Note added to documentation

hail_install_note

---

getting_started.md

Previous PR merged without addressing linter complaint - whitespace removed from empty line

trim_whitespace_in_md

---

.pre-commit-config.yaml
new_repository/flake8
new_repository/pre-commit-config.yaml
new_repository/pylintrc

* Update version pins in the pre-commit config
* Specify python version for pre-commit environment (to make sure it recognises latest python syntax)
* Disable some arguably not helpful inspections

Pre-commit template update

---

hail_batch_dev.md

Column names have changed slightly.

Hail Batch dev setup docs: update db column names

---

.github/workflows/lint.yaml
.pre-commit-config.yaml
getting_started.md
hail_batch_dev.md
infrastructure.md
new_repository.md
new_repository/flake8
new_repository/pre-commit-config.yaml
new_repository/pylintrc
pre-commit.md
storage_policies/README.md

added a reference to the template when creating a new repo
small changes for the linter
didn't alter the rest of the document structure

add references to template repository

---

storage_policies/README.md

https://github.com/populationgenomics/analysis-runner/pull/479

Rename "release-requestery-pays" -> "requester-pays"

---

getting_started.md

Context: https://centrepopgen.slack.com/archives/C018KFBCR1C/p1669260337633449

Mention how to set up real-time Slack notifications for GitHub

---

storage_policies/README.md

See https://github.com/populationgenomics/cpg-infrastructure/pull/75 for the corresponding implementation change.

Update the storage policies to reflect Autoclass changes

---

hail_batch_dev.md

Add forgotten commit on top of https://github.com/populationgenomics/team-docs/pull/135.

Add docker group step

---

README.md
budgets.md

I've drafted a few cases, but happy to take more suggestions for examples I can write out an action plan for.

Add guide to CPG budgets

---

python.md

Added a brief and simple example of how we want our Python type annotations to look like. Keen to add more info if it would help (why we went with this decision etc).

Added type annotation policy

---

cpg-infrastructure/developer.rst
cpg-infrastructure/user.rst
index.rst

First pass of documentation. Would love some initial feedback on areas that are undercooked.
Will eventually look for a review from PM team + other users.

Add user + developer docs for cpg-infrastructure

---

index.rst
kubernetes.md

Something I've had lying around in draft for a while…

Add Kubernetes commands cheatsheet

---

bioinformatics/igv.md
hail.md
kubernetes.md

Draft for now, until I run out of things to update…

Hail-related documentation updates
